---
extends:
  - next/core-web-vitals
  - plugin:import/recommended
  - plugin:react-hooks/recommended
plugins:
  - import
settings:
  import/ignore:
    - node_modules
    - \\.json$
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
rules:
  import/no-unresolved: 2
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/imports-first: 2
  import/no-duplicates: 2
  import/newline-after-import: 2
